openapi: 3.0.0
info:
  title: Login API
  version: 1.0.0

paths:
  /api/login_api:
    post:
      summary: "사용자 로그인"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                  description: "로그인 아이디(이메일)"
                password:
                  type: string
                  minLength: 8
                  description: "대소문자+숫자+특수기호 8자리 이상"
      responses:
        "200":
          description: "로그인 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  userId:
                    type: string
        "400":
          description: "요청 값 오류"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    enum:
                      - INVALID_EMAIL_FORMAT
                      - INVALID_PASSWORD_FORMAT
                      - MISSING_REQUIRED_FIELD
        "401":
          description: "인증 실패"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    enum:
                      - LOGIN_FAILED
