openapi: 3.0.3
info:
  title: 로그인 기능 API
  version: 1.0.0
  description: 사용자 로그인 API
paths:
  /api/login_api:
    post:
      summary: 사용자 로그인 API
      tags:
      - auth
      - login
      requestBody:
        description: 로그인 요청 바디
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: 로그인 이메일
                password:
                  type: string
                  minLength: 8
                  pattern: (?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!@#$%^&*]).{8,}
                  description: 대문자/소문자/숫자/특수문자를 모두 포함한 8자리 이상
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: 액세스 토큰
                  userId:
                    type: string
                    description: 사용자 ID
                required:
                - accessToken
                - userId
        '400':
          description: 요청 값 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                required:
                - errorCode
              examples:
                invalid_password_format:
                  summary: 비밀번호 형식 오류
                  value:
                    errorCode: INVALID_PASSWORD_FORMAT
        '401':
          description: 인증 실패 또는 계정 잠김
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                required:
                - errorCode
              examples:
                login_failed:
                  summary: 이메일 또는 비밀번호 불일치
                  value:
                    errorCode: LOGIN_FAILED
                account_locked:
                  summary: 계정 잠김 상태
                  value:
                    errorCode: ACCOUNT_LOCKED
