openapi: 3.0.3
info:
  title: 사용자 로그인 API
  version: 1.0.0
  description: 사용자가 이메일과 비밀번호로 로그인하는 기능. 로그인 성공 시 accessToken과 userId를 반환한다.
paths:
  /api/login_api:
    post:
      summary: 사용자 로그인 API
      tags:
      - auth
      - login
      requestBody:
        description: 로그인 요청 바디
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: 로그인 이메일
                password:
                  type: string
                  minLength: 8
                  pattern: (?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!@#$%^&*]).{8,}
                  description: 로그인 비밀번호
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: 액세스 토큰
                  userId:
                    type: string
                    description: 사용자 ID
        '400':
          description: 요청 값 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: INVALID_PASSWORD_FORMAT
        '401':
          description: 인증 실패(이메일 또는 비밀번호 불일치)
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: LOGIN_FAILED
